---
- name: "Debug - Output docker-compose.yml object"
  ansible.builtin.debug:
    msg: "{{ lookup('template', 'docker-compose.yml.j2') }}"
  when: is_development | default (false, true)
  tags:
    - debug

- name: Deploy Chrome
  community.docker.docker_stack:
    name: "fad"
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"
    state: present
  changed_when: false
