load_defaults: 7.25.3
development:
  adapter: solr
  url: <%= Settings.solr.url %>
test: &test
  adapter: solr
  url: <%= Settings.solr.url %>
staging:
  adapter: solr
  url: <%= Settings.solr.url %>
production:
  adapter: solr
  url: <%= Settings.solr.url %>
