# Jobs scheduled via sidekiq-cron

harvest_all:
  cron: <%= Rails.env.production? ? "0 5 * * 1,3,5" : "0 1 * * 1,3,5" %> # production: 5AM MWF, staging/other: 1AM MWF
  class: "PartnerHarvestEnqueueJob"
  description: "Enqueues PartnerHarvestJobs for all Endpoints sorted by oldest updated_at value"
  active_job: true
build_sitemap:
  cron: "0 9 * * 1,3,5" # 9AM MWF
  class: "BuildSitemapJob"
  description: "Rebuilds sitemap after harvest"
  active_job: true
delete_searches:
  cron: "0 1 * * *" # Daily
  class: "DeleteSearchesJob"
  description: "Remove searches that are older than 7 days"
  active_job: true
