pennlibs_web_version: '1.5.0'

homepage_images:
  - file: moelis-reading-room.jpg
    alt_text: An archival reading room

solr:
  url: <%= ENV['SOLR_URL'] %>

honeybadger:
  api_key: <%= DockerSecrets.lookup('honeybadger_api_key') %>

aspace_throttle: 0.5

