pennlibs_web_version: '1.4.0-dev.4'

aeon:
  url: 'https://aeon.library.upenn.edu'

solr:
  url: <%= ENV['SOLR_URL'] %>

honeybadger:
  api_key: <%= DockerSecrets.lookup('honeybadger_api_key') %>

aspace_throttle: 0.5

