---
is_development: true

# expose the docker api (only for dev env) to allow IDE's to add remote interpreters for debugging
docker_daemon_hosts:
  - "tcp://0.0.0.0:2376"
  - "unix:///var/run/docker.sock"

docker_daemon_config:
  debug: true
  default-ulimits:
    nofile:
      Name: "nofile"
      Hard: 1048576
      Soft: 1048576

skip_firewall: true
skip_docker_group: true
skip_docker_user: true
skip_docker_install: true
skip_docker_repo_setup: true
skip_install_deps: true
skip_docker_config: true
