include:
  - project: "devops/gitlab/ci-templates/deploy"
    file: ".hashicorp_vault.yml"
  - project: "devops/gitlab/ci-templates/docker"
    ref: "multiarch"
    file:
      - ".amend_manifests.yml"
      - ".build_and_push_docker_images.yml"
      - ".copy_docker_images.yml"
      - ".remove_tmp_registry.yml"
  - project: "devops/gitlab/ci-templates/ruby"
    ref: "sans-dind"
    file: 
      - ".rspec.yml"
      - ".rubocop.yml"
  - project: "devops/gitlab/ci-templates/sast"
    ref: "master"
    file:
      - ".trivy_container_scanning.yml"
  - template: "Workflows/MergeRequest-Pipelines.gitlab-ci.yml"

stages:
  - build_and_push:tmp_base_image
  - build_and_push:tmp_dev_image
  - amend_tmp_base_dev_images
  - build_and_push:tmp_solr_image
  - amend_tmp_solr_image
  - test
  - build_and_push:tmp_prod_image
  - amend_prod_image
  - sast
  - copy_docker_images
  - remove_tmp_registry
  - deploy

# -- Start - build and push base image
build_and_push_base_app_image:
  stage: build_and_push:tmp_base_image
  extends:
    - .build_and_push_docker_images
  parallel:
    matrix:
      - RUNNER: build-arm
        DOCKER_BUILD_PLATFORM: "linux/arm64"
      - RUNNER: build
        DOCKER_BUILD_PLATFORM: "linux/amd64"
  variables:
    DOCKER_BUILD_CONTEXT: "ansible/roles/finding_aid_discovery/files/src/"
    DOCKER_TARGET: "base"
    DOCKERFILE_PATH: "ansible/roles/finding_aid_discovery/files/src/"
    IMAGE_CACHE_TAG: "app"
    REGISTRY_REPOSITORY: "${CI_PIPELINE_ID}/app"
  tags:
    - ${RUNNER}
# -- End - build and push base image

# -- Start - build, push temp dev image
build_and_push_dev_app_image:
  stage: build_and_push:tmp_dev_image
  extends:
    - .build_and_push_docker_images
  parallel:
    matrix:
      - RUNNER: build-arm
        DOCKER_BUILD_PLATFORM: "linux/arm64"
      - RUNNER: build
        DOCKER_BUILD_PLATFORM: "linux/amd64"
  variables:
    DOCKER_BUILD_ARGS: "--build-arg RAILS_ENV=development"
    DOCKER_BUILD_CONTEXT: "ansible/roles/finding_aid_discovery/files/src/"
    DOCKER_TARGET: "development"
    DOCKERFILE_PATH: "ansible/roles/finding_aid_discovery/files/src/"
    IMAGE_CACHE_TAG: "app"
    REGISTRY_REPOSITORY: "${CI_PIPELINE_ID}/app"
  needs:
    - build_and_push_base_app_image
  tags:
    - ${RUNNER}
# -- End - build, push temp dev image

amend_tmp_base_dev_images:
  stage: amend_tmp_base_dev_images
  extends:
    - .amend_manifests
  needs:
    - build_and_push_base_app_image
    - build_and_push_dev_app_image
  variables:
    REGISTRY_REPOSITORY: "${CI_PIPELINE_ID}/app"
  tags:
    - build

# -- Start - build and push temp solr image
build_and_push_solr_image:
  stage: build_and_push:tmp_solr_image
  extends:
    - .build_and_push_docker_images
  parallel:
    matrix:
      - RUNNER: build-arm
        DOCKER_BUILD_PLATFORM: "linux/arm64"
      - RUNNER: build
        DOCKER_BUILD_PLATFORM: "linux/amd64"
  variables:
    DOCKER_BUILD_CONTEXT: "ansible/roles/solr/files/src/"
    DOCKERFILE_PATH: "ansible/roles/solr/files/src/"
    IMAGE_CACHE_TAG: "solr"
    REGISTRY_REPOSITORY: "${CI_PIPELINE_ID}/solr"
  tags:
    - ${RUNNER}
# -- End - build and push temp solr image

amend_tmp_solr_image:
  stage: amend_tmp_solr_image
  extends:
    - .amend_manifests
  needs:
    - build_and_push_solr_image
  variables:
    REGISTRY_REPOSITORY: "${CI_PIPELINE_ID}/solr"
  tags:
    - build

# -- Start - test dev image
rspec_app_test:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/${CI_PIPELINE_ID}/app:${CI_COMMIT_SHORT_SHA}-development
  services:
    - name: browserless/chrome:1.59-puppeteer-1.20.0
      alias: chrome
    - postgres:14
    - name: ${CI_REGISTRY_IMAGE}/${CI_PIPELINE_ID}/solr:${CI_COMMIT_SHORT_SHA}
      alias: solr
  extends:
    - .rspec
  variables:
    CHROME_URL: "http://chrome:3000"
    CONNECTION_TIMEOUT: -1
    CONFIG_LOCATION: "/finding_aid_discovery_configs"
    CORE_NAME: "finding-aid-discovery-core"
    DATABASE_NAME: "finding_aid_discovery"
    DATABASE_PASSWORD: "rspec_test"
    DATABASE_USER: "rspec_test"
    FF_NETWORK_PER_BUILD: "true"
    FINDING_AID_DISCOVERY_URL: "findingaids.test.com"
    POSTGRES_DB: "finding_aid_discovery"
    POSTGRES_PASSWORD: "rspec_test"
    POSTGRES_USER: "rspec_test"
    RAILS_ENV: "test"
    RAILS_SYSTEM_TESTING_SCREENSHOT_HTML: "1"
    SOLR_URL: "http://solr:8983/solr/finding-aid-discovery-core"
  script:
    - cd ${CI_PROJECT_DIR}/ansible/roles/finding_aid_discovery/files/src/
    - bundle add rspec_junit_formatter
    - bundle exec rake db:migrate
    - bundle exec rspec --format progress --format RspecJunitFormatter --out rspec.xml
  needs:
    - amend_tmp_base_dev_images
    - amend_tmp_solr_image
  coverage: '/\(\d+.\d+\%\) covered/'
  artifacts:
    paths:
      - ansible/roles/finding_aid_discovery/files/src/tmp/coverage/index.html
      - ansible/roles/finding_aid_discovery/files/src/tmp/capybara
      - ansible/roles/finding_aid_discovery/files/src/rspec.xml
    expire_in: 1 week
    reports:
      junit: ansible/roles/finding_aid_discovery/files/src/rspec.xml
  rules:
    - if: $DISABLE_RSPEC_TEST == "true"
      when: never
    - exists:
        - ansible/roles/finding_aid_discovery/files/src/spec/**.rb
        - ansible/roles/finding_aid_discovery/files/src/spec/**/**.rb
  tags:
    - build

rubocop_app_test:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/${CI_PIPELINE_ID}/app:${CI_COMMIT_SHORT_SHA}-development
  needs:
    - amend_tmp_base_dev_images
  extends:
    - .rubocop
  before_script:
    - cd ansible/roles/finding_aid_discovery/files/src/
  rules:
    - if: $DISABLE_RUBOCOP == "true"
      when: never
    - exists:
        - ansible/roles/finding_aid_discovery/files/src/.rubocop.yml
  tags:
    - build
# -- End - test dev image

# -- Start - build and push temp prod image
build_and_push_prod_app_image:
  stage: build_and_push:tmp_prod_image
  extends:
    - .build_and_push_docker_images
  parallel:
    matrix:
      - RUNNER: build-arm
        DOCKER_BUILD_PLATFORM: "linux/arm64"
      - RUNNER: build
        DOCKER_BUILD_PLATFORM: "linux/amd64"
  variables:
    DOCKER_BUILD_ARGS: "--build-arg RAILS_ENV=production"
    DOCKER_BUILD_CONTEXT: "ansible/roles/finding_aid_discovery/files/src/"
    DOCKER_TARGET: "production"
    DOCKERFILE_PATH: "ansible/roles/finding_aid_discovery/files/src/"
    IMAGE_CACHE_TAG: "app"
    REGISTRY_REPOSITORY: "${CI_PIPELINE_ID}/app"
  needs:
    - rspec_app_test
    - rubocop_app_test
  tags:
    - ${RUNNER}
# -- End - build and push temp prod image

amend_prod_image:
  stage: amend_prod_image
  extends:
    - .amend_manifests
  needs:
    - build_and_push_prod_app_image
  variables:
    DOCKER_TARGET: "production"
    REGISTRY_REPOSITORY: "${CI_PIPELINE_ID}/app"
    TAG_WITH_DOCKER_TARGET: "false"
  tags:
    - build

# -- Start - SAST images
# Test application image
trivy_app_container_scanning:
  stage: sast
  extends:
    - .trivy_container_scanning
  before_script:
    - apk add --no-cache docker
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  after_script:
    - docker logout ${CI_REGISTRY}
  needs:
    - amend_prod_image
  variables:
    CI_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/${CI_PIPELINE_ID}/app:${CI_COMMIT_SHORT_SHA}
  tags:
    - build
  allow_failure: true

# Test solr image
trivy_solr_container_scanning:
  stage: sast
  extends:
    - .trivy_container_scanning
  before_script:
    - apk add --no-cache docker
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  after_script:
    - docker logout ${CI_REGISTRY}
  needs:
    - rspec_app_test
  variables:
    CI_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/${CI_PIPELINE_ID}/solr:${CI_COMMIT_SHORT_SHA}
  tags:
    - build
  allow_failure: true
# -- End - SAST images

# -- Start - Copy app docker images
copy_app_docker_images:
  stage: copy_docker_images
  variables:
    ORIGINAL_REGISTRY_REPOSITORY: "${CI_PIPELINE_ID}/app"
    FINAL_REGISTRY_REPOSITORY: "app"
  needs:
    - trivy_app_container_scanning
  extends:
    - .copy_docker_images
  tags:
    - build
# -- End - Copy app docker images

# -- Start - Copy solr docker images
copy_solr_docker_images:
  stage: copy_docker_images
  variables:
    ORIGINAL_REGISTRY_REPOSITORY: "${CI_PIPELINE_ID}/solr"
    FINAL_REGISTRY_REPOSITORY: "solr"
  needs:
    - trivy_solr_container_scanning
  extends:
    - .copy_docker_images
  tags:
    - build
# -- End - Copy solr docker images

# -- Start - remove tmp registry repository
remove_tmp_registry:
  stage: remove_tmp_registry
  extends:
    - .remove_tmp_registry
  rules:
    - when: always
  needs:
    - copy_app_docker_images
    - copy_solr_docker_images
  allow_failure: true
  tags:
    - build
# -- End - remove tmp registry repository

# Deploy staging
deploy_staging:
  stage: deploy
  extends:
    - .deploy
  variables:
    IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}
  environment:
    name: staging
    url: https://pacscl-staging.library.upenn.edu/
  needs:
    - copy_app_docker_images
    - copy_solr_docker_images
  only:
    - main
  tags:
    - deploy

# Deploy production
deploy_production:
  stage: deploy
  extends:
    - .deploy
  variables:
    IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}
  environment:
    name: production
    url: https://findingaids.library.upenn.edu/
  needs:
    - copy_app_docker_images
    - copy_solr_docker_images
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(\.[a-zA-Z0-9]+)?$/
  tags:
    - deploy
# -- End - deployment
