---
nginx:
  image:
    name: "nginx"
    tag: "1.25.1"
  port: 80
  replicas: 2
  urls:
    - "pacscl01.library.upenn.int"
    - "pacscl-staging.library.upenn.edu"
  versioned_configs:
    default_conf:
      filename: "default.conf.j2"
      version: 6
    nginx_conf:
      filename: "nginx.conf.j2"
      version: 3
