---
redis_users:
  - name: "sidekiq"
    acl_rules: "+@all ~*"
    password: "{{ finaids_vault_values.secret.redis_sidekiq_password }}"
    version: "{{ finaids_vault_values.metadata.version }}"
  - name: "default"
    acl_rules: "+@all ~*"
    password: "{{ finaids_vault_values.secret.redis_default_password }}"
    version: "{{ finaids_vault_values.metadata.version }}"
