---
finding_aid_discovery:
  build_docker_image: false
  dev:
    build_path: "/app/roles/finding_aid_discovery/files/src"
    volume_path: "{{ lookup('ansible.builtin.env', 'BASE_DIR') }}/ansible/roles/finding_aid_discovery/files/src/"
  image:
    name: "finding_aid_discovery"
    registry: "gitlab.library.upenn.edu/pacscl/finding-aid-discovery/app"
    tag: "main-development"
  port: 4567
  rails_env: "development"
  replicas: 1
  url: "finding-aid-discovery-dev.library.upenn.edu"
  versioned_secrets:
    honeybadger_api_key:
      value: "{{ finding_aid_discovery_vault.versioned_secrets.honeybadger_api_key.value }}"
      version: 1
    penn_aspace_api_username:
      value: "{{ finding_aid_discovery_vault.versioned_secrets.penn_aspace_api_username.value }}"
      version: 1
    penn_aspace_api_password:
      value: "{{ finding_aid_discovery_vault.versioned_secrets.penn_aspace_api_password.value }}"
      version: 2
    rails_master_key:
      value: "{{ finding_aid_discovery_vault.versioned_secrets.rails_master_key.value }}"
      version: 1
