---
postgres:
  database: "finding_aid_discovery"
  dev_env:
    log_connections: "on"
    log_disconnections: "on"
    log_statement: "all"
  image:
    name: "postgres"
    tag: "14"
  replicas: 1
  secrets:
    password:
      value: "{{ vault_postgres.password.value }}"
      version: 1
  user: "finding_aid_discovery"
