repos:
  - repo: local
    hooks:
      - id: gitleaks-docker
        name: Gitleaks via docker
        entry: zricethezav/gitleaks:v7.2.0 gitleaks -v -q --config-path=/src/.gitleaks.toml --path=/src
        language: docker_image
        always_run: true
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.4.0
    hooks:
      - id: ansible-lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length=120"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"
        always_run: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-toml
        always_run: true
      - id: check-yaml
        always_run: true
