# -*- mode: ruby -*-
# vi: set ft=ruby :

# Arrange nodes in reverse order so the manager is the last vm to be provisioned
cluster = {
  "finding-aid-discovery-manager" => { :ip => "10.10.2.206", :cpus => 2, :mem => 4096, :port => 2020 }
}

# Class to grab the ansible vault password from a hashicorp vault v2 endpoint
class Password
  def to_s
    print "HashiCorp Vault username: "
    hv_user = STDIN.gets.chomp

    print "HashiCorp Vault password: "
    hv_pass = STDIN.noecho(&:gets).chomp

    Vault.address = "https://vault.library.upenn.edu"
    Vault.auth.ldap(hv_user, hv_pass)
    results = Vault.logical.read("ansible/data/vault/finding-aid-discovery/vagrant").data
    results.dig(:data, :password)
  end
end

Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-hostsupdater", "vagrant-vbguest", "vault"]

  if Vagrant::Util::Platform::darwin?
    config.vagrant.plugins << "vagrant-parallels"
    box = "bento/ubuntu-22.04-arm64"
  else
    box = "bento/ubuntu-20.04"
  end

  # Add domains to hosts file
  config.hostsupdater.aliases = {
    "10.10.2.206" => [
      "finding-aid-discovery-dev.library.upenn.edu"
    ]
  }

  cluster.each_with_index do |(hostname, info), index|
    config.vm.box = box

    # Use the default insecure key as this is only used for development
    config.ssh.insert_key = false

    config.vm.define hostname do |cfg|
      cfg.vm.network :private_network, ip: "#{info[:ip]}"
      cfg.vm.network :forwarded_port, id: "ssh", host: info[:port], guest: 22
      cfg.vm.hostname = hostname

      # Virtualbox provider
      cfg.vm.provider :virtualbox do |vb, override|
        vb.name = hostname
        vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
        # push the first interface far out enough to minimize potential conflict with docker swarm
        # which defaults to 10.0.0.0/8 for networks/containers
        vb.customize ["modifyvm", :id, "--natnet1", "10.252/16"]
      end

      # Parallels provider
      cfg.vm.provider :parallels do |prl, override|
        prl.name = hostname
        prl.memory = info[:mem]
        prl.cpus = info[:cpus]
      end

      config.vm.box = box

      # Run the ansible playbook after the manager vm has been provisioned
      if hostname == "finding-aid-discovery-manager"
        # Add volumes for development
        cfg.vm.synced_folder "../", "/finding_aid_discovery"

        # Get the vault password and assign it to a tmp file
        cfg.vm.provision "shell", env: {"VAULT_PASS" => Password.new}, inline: <<-SHELL
          printf '%s\n' "${VAULT_PASS}" > /tmp/vault_pass
        SHELL

        cfg.vm.provision :ansible_local do |ansible|
          ansible.config_file = "/finding_aid_discovery/ansible/ansible.vagrant.cfg"
          ansible.extra_vars = {
            ansible_python_interpreter: "/usr/bin/env python3"
          }
          ansible.install_mode = "pip3"
          ansible.inventory_path = "/finding_aid_discovery/ansible/inventories/vagrant"
          ansible.galaxy_role_file = "/finding_aid_discovery/ansible/roles/requirements.dev.yml"
          ansible.galaxy_roles_path = "/finding_aid_discovery/ansible/roles"
          ansible.galaxy_command = "ansible-galaxy install -r %{role_file} --force"
          ansible.limit = "all"
          ansible.playbook = "/finding_aid_discovery/ansible/vagrant.yml"
          ansible.vault_password_file = "/tmp/vault_pass"
          ansible.verbose = false
        end

        cfg.trigger.after [:provision, :reload, :resume, :up] do |trigger|
          trigger.info = "Removing vault password"
          trigger.run_remote = { inline: <<-SHELL
              rm -fr /tmp/vault_pass
            SHELL
          }
        end

      end
    end
  end
end
