# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.5'

gem 'archivesspace-client'
gem 'blacklight', '~> 8'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'bootstrap', '~> 4.0'
gem 'bootstrap_form', '~> 4.0'
gem 'config'
gem 'devise'
gem 'honeybadger'
gem 'iso-639'
gem 'jbuilder', '~> 2.7'
gem 'jquery-rails'
gem 'net-imap', require: false
gem 'net-pop', require: false
gem 'net-smtp', require: false
gem 'omniauth'
gem 'omniauth-rails_csrf_protection'
gem 'omniauth-saml'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rails', '~> 7.2.0'
gem 'rainbow'
gem 'retryable'
gem 'rsolr', '>= 1.0', '< 3'
gem 'sass-rails', '>= 6'
gem 'sidekiq-cron'
gem 'sidekiq-pro', source: 'https://gems.contribsys.com'
gem 'sitemap_generator'
gem 'turbolinks', '~> 5'
gem 'twitter-typeahead-rails', '0.11.1.pre.corejavascript'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'upennlib-rubocop', require: false

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'debug'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails', '~> 7.0'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'web-console', '>= 4.1.0'
end

group :test do
  gem 'capybara'
  gem 'cuprite'
  gem 'simplecov', require: false
  gem 'webmock'
end
