---
- name: Create traefik dir
  file:
    path: "{{ project_root ~ '/traefik' }}"
    state: directory

- name: Copy docker-compose.yml file
  copy:
    src: "docker-compose.yml"
    dest: "{{ project_root ~ '/traefik/docker-compose.yml' }}"

- name: Create traefik users file
  htpasswd:
    path: "{{ project_root ~ '/users' }}"
    name: "{{ item.key }}"
    password: "{{ item.value | string | password_hash('md5', traefik.middlewares_auth.salt) }}"
    crypt_scheme: "plaintext"
  with_dict: "{{ traefik.middlewares_auth.users }}"
  no_log: true

- name: Get traefik users data from file
  slurp:
    src: "{{ project_root ~ '/users' }}"
  register: users
  no_log: true

- name: Create traefik middlewares users
  docker_secret:
    name: "{{ 'traefik_middlewares_users_v' ~ traefik.middlewares_auth.version }}"
    data: "{{ users['content'] | b64decode }}"
    state: present
  no_log: true

- name: Delete traefik users file
  file:
    path: "{{ project_root ~ '/users' }}"
    state: absent
  no_log: true

- name: Deploy traefik
  docker_stack:
    name: "fad"
    compose:
      - "{{ project_root ~ '/traefik/docker-compose.yml' }}"
    state: present
  changed_when: false
  environment:
    TRAEFIK_DASHBOARD_ENABLE: "{{ traefik.dashboard.enable }}"
    TRAEFIK_DASHBOARD_PORT: "{{ traefik.dashboard.port }}"
    TRAEFIK_IMAGE_NAME: "{{ traefik.image.name }}"
    TRAEFIK_IMAGE_TAG: "{{ traefik.image.tag }}"
    TRAEFIK_MIDDLEWARES_USERS_NAME: "{{ 'traefik_middlewares_users_v' ~ traefik.middlewares_auth.version }}"
    TRAEFIK_LOG_LEVEL: "{{ traefik.log_level }}"
    TRAEFIK_URL: "{{ traefik.url }}"
