version: "3.8"

services:
  sidekiq:
    image: ${FINDING_AID_DISCOVERY_IMAGE_NAME}:${FINDING_AID_DISCOVERY_IMAGE_TAG}
    command: ["bundle", "exec", "sidekiq"]
    deploy:
      placement:
        constraints:
          - "node.labels.sidekiq == true"
      replicas: ${REPLICAS}
      update_config:
        order: "start-first"
        parallelism: 1
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: /run/secrets/database_password
      DATABASE_USER: ${DATABASE_USER}
      FINDING_AID_DISCOVERY_URL: ${FINDING_AID_DISCOVERY_URL}
      REDIS_SIDEKIQ_USER: ${REDIS_SIDEKIQ_USER}
      REDIS_URL: "redis://redis:${REDIS_PORT}/0"
      SOLR_URL: "http://solr:8983/solr/${SOLR_CORE_NAME}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "ps aux | grep '[s]idekiq 6' || exit 1",
        ]
      interval: 30s
      retries: 3
      start_period: 1m
      timeout: 30s
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: "10m"
    networks:
      - database
      - redis
      - solr
    secrets:
      - database_password
      - penn_aspace_api_password
      - penn_aspace_api_username
      - redis_sidekiq_password
networks:
  database:
    external: true
  redis:
    external: true
  solr:
    external: true

secrets:
  database_password:
    external: true
    name: ${DATABASE_PASSWORD}
  penn_aspace_api_password:
    external: true
    name: ${FINDING_AID_DISCOVERY_PENN_ASPACE_API_PASSWORD}
  penn_aspace_api_username:
    external: true
    name: ${FINDING_AID_DISCOVERY_PENN_ASPACE_API_USERNAME}
  redis_sidekiq_password:
    external: true
    name: ${REDIS_SIDEKIQ_PASSWORD}
    
