version: "3.8"

services:
  sidekiq:
    environment:
      APP_UID: ${UID:-1000}
      APP_GID: ${GID:-1000}
    volumes:
      - /finding_aid_discovery/ansible/roles/finding_aid_discovery/files/src/:/home/app
