---
all:
  children:
    docker_engine:
      children:
        staging:
          hosts:
            swarm-01:
              ansible_host: "{{ ansible_host }}"
              ansible_connection: local
      vars:
        ansible_user: vagrant
    docker_swarm_manager:
      hosts:
        swarm-01:
          swarm_labels: ["finding_aid_discovery", "nginx", "postgres", "solr", "traefik"]
