default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: finding_aid_discovery_development

test:
  <<: *default
  database: finding_aid_discovery_test

production:
  <<: *default
  database: finding_aid_discovery_production
  username: finding_aid_discovery_development
  password: <%= ENV['FINDING_AID_DISCOVERY_DATABASE_PASSWORD'] %>
