version: "3.8"

services:
  solr:
    image: ${SOLR_IMAGE_NAME}:${SOLR_IMAGE_TAG}
    deploy:
      placement:
        constraints:
          - "node.labels.solr == true"
      update_config:
        order: "start-first"
        parallelism: 1
      replicas: ${REPLICAS}
    environment:
      CONFIG_LOCATION: ${SOLR_CONFIG_LOCATION}
      CORE_NAME: ${SOLR_CORE_NAME}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsSL localhost:8983/solr || exit 1",
        ]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 3m
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: "10m"
    networks:
      - solr
    volumes:
      - solr_data:/var/solr/data

networks:
  solr:
    external: true

volumes:
  solr_data:
