---
nginx:
  image:
    name: "nginx"
    tag: "1.25.1"
  port: 80
  replicas: 1
  urls:
    - "finding-aid-discovery-dev.library.upenn.edu"
  versioned_configs:
    default_conf:
      filename: "default.conf.j2"
      version: 1
    nginx_conf:
      filename: "nginx.conf.j2"
      version: 2