---
finding_aid_discovery_build_docker_image: true
finding_aid_discovery_docker_image_name: "finding_aid_discovery"
finding_aid_discovery_docker_image_registry: "gitlab.library.upenn.edu/dld/finding-aids"
finding_aid_discovery_docker_image_tag: "main-development"
finding_aid_discovery_port: 4567
finding_aid_discovery_rails_env: "development"
finding_aid_discovery_replicas: 1
finding_aid_discovery_solr_url: "http://solr-1:8983/solr/finding-aid-discovery-development"
finding_aid_discovery_solr_test_url: "http://solr-1:8983/solr/finding-aid-discovery-test"
finding_aid_discovery_url: "finding-aid-discovery-dev.library.upenn.edu"

finding_aid_discovery_versioned_secrets:
  slack_notification_email_address:
    value: "sample-slack@upennlts.slack.com"
    version: 1
  honeybadger_api_key:
    value: "123456"
    version: 1
  penn_aspace_api_username:
    value: "sample"
    version: 1
  penn_aspace_api_password:
    value: "123456"
    version: 1
