---
finding_aid_discovery:
  build_docker_image: false
  image:
    name: "finding_aid_discovery"
    registry: "gitlab.library.upenn.edu/pacscl/finding-aid-discovery/app"
    tag: "main-development"
  port: 4567
  replicas: 1
  url: "finding-aid-discovery-dev.library.upenn.edu"
  versioned_secrets:
    honeybadger_api_key:
      value: "123456"
      version: 1
    penn_aspace_api_username:
      value: "sample"
      version: 1
    penn_aspace_api_password:
      value: "123456"
      version: 1
