---
finding_aid_discovery:
  build_docker_image: false
  dev:
    build_path: "/finding_aid_discovery/ansible/roles/finding_aid_discovery/files/src/"
    volume_path: "/finding_aid_discovery/ansible/roles/finding_aid_discovery/files/src/"
  image:
    name: "finding_aid_discovery"
    registry: "gitlab.library.upenn.edu/pacscl/finding-aid-discovery/app"
    tag: "main-development"
  port: 4567
  rails_env: "development"
  replicas: 1
  url: "finding-aid-discovery-dev.library.upenn.edu"
  versioned_secrets:
    honeybadger_api_key:
      value: "123456"
      version: 1
    penn_aspace_api_username:
      value: "sample"
      version: 1
    penn_aspace_api_password:
      value: "123456"
      version: 1
