---
finding_aid_discovery_build_docker_image: true
finding_aid_discovery_docker_image_name: "finding_aid_discovery"
finding_aid_discovery_docker_image_registry: "gitlab.library.upenn.edu/dld/finding-aids"
finding_aid_discovery_docker_image_tag: "main-development"
finding_aid_discovery_port: 4567
finding_aid_discovery_rails_env: "development"
finding_aid_discovery_replicas: 1
finding_aid_discovery_solr_url: "http://solr-1:8983/solr/finding-aid-discovery-development"
finding_aid_discovery_solr_test_url: "http://solr-1:8983/solr/finding-aid-discovery-test"
finding_aid_discovery_url: "finding-aid-discovery-dev.library.upenn.edu"

finding_aid_discovery_versioned_secrets:
  slack_notification_email_address:
    vault: finaids_vault_values
  honeybadger_api_key:
    vault: finaids_vault_values
  upenn_aspace_username:
    vault: finaids_vault_values
  upenn_aspace_password:
    vault: finaids_vault_values
