---
solr:
  admin_port: "8983"
  build_docker_image: false
  config_location: "/finding_aid_discovery_configs"
  core_name: "finding-aid-discovery-core"
  image:
    name: "solr"
    registry: "gitlab.library.upenn.edu/dld/finding-aids/solr"
    tag: "main"
  java:
    memory:
      min: "512m"
      max: "512m"
  replicas: 1
