version: "3.8"

services:
  finding_aid_discovery:
    deploy:
      labels:
        - "traefik.http.routers.fad.middlewares=fad_https"
        - "traefik.http.middlewares.fad_https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.fad_https.redirectscheme.permanent=true"

        - "traefik.http.routers.fad_secure.entrypoints=websecure"
        - "traefik.http.routers.fad_secure.rule=host(`${FINDING_AID_DISCOVERY_URL}`)"
        - "traefik.http.routers.fad_secure.service=fad_secure"
        - "traefik.http.services.fad_secure.loadbalancer.server.port=${FINDING_AID_DISCOVERY_PORT}"

        - "traefik.http.routers.fad_secure.tls=true"
        - "traefik.http.routers.fad_secure.tls.certresolver=letsencrypt"
    environment:
      APP_UID: ${UID:-1000}
      APP_GID: ${GID:-1000}
      CHROME_URL: "http://chrome:${CHROME_PORT}"
    healthcheck:
      retries: 20
      start_period: 5m
    volumes:
      - /finding_aid_discovery/ansible/roles/finding_aid_discovery/files/src/:/home/app
