version: "3.8"

services:
  finding_aid_discovery:
    image: ${FINDING_AID_DISCOVERY_IMAGE_NAME}:${FINDING_AID_DISCOVERY_IMAGE_TAG}
    command: ["bundle", "exec", "puma", "-b", "tcp://0.0.0.0:${FINDING_AID_DISCOVERY_PORT}"]
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.fad.entrypoints=web"
        - "traefik.http.routers.fad.rule=Host(`${FINDING_AID_DISCOVERY_URL}`)"
        - "traefik.http.routers.fad.service=fad"
        - "traefik.http.services.fad.loadbalancer.server.port=${FINDING_AID_DISCOVERY_PORT}"

        - "traefik.http.routers.fad.middlewares=fad-http-cache"
        - "traefik.http.middlewares.fad-http-cache.plugin.souin.default_cache.ttl=3600s"
        - "traefik.http.middlewares.fad-http-cache.plugin.souin.default_cache.default_cache_control=public,max-age=43200"
      placement:
        constraints:
          - "node.labels.finding_aid_discovery == true"
      replicas: ${REPLICAS}
      update_config:
        order: "start-first"
        parallelism: 1
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: /run/secrets/database_password
      DATABASE_USER: ${DATABASE_USER}
      FINDING_AID_DISCOVERY_URL: ${FINDING_AID_DISCOVERY_URL}
      RAILS_ENV: ${FINDING_AID_DISCOVERY_RAILS_ENV}
      RAILS_LOG_TO_STDOUT: "true"
      SOLR_URL: "${FINDING_AID_DISCOVERY_SOLR_URL}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsSL localhost:${FINDING_AID_DISCOVERY_PORT}/about || exit 1",
        ]
      interval: 30s
      retries: 6
      start_period: 30s
      timeout: 30s
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: "10m"
    networks:
      - database
      - finding_aid_discovery
      - traefik
    secrets:
      - database_password
      - slack_notification_email_address
      - honeybadger_api_key
      - penn_aspace_api_password
      - penn_aspace_api_username
      - rails_master_key

networks:
  database:
    external: true
  finding_aid_discovery:
    driver: overlay
    name: finding_aid_discovery
    attachable: true
  traefik:
    external: true

secrets:
  database_password:
    external: true
    name: ${DATABASE_PASSWORD}
  honeybadger_api_key:
    external: true
    name: ${FINDING_AID_DISCOVERY_HONEYBADGER_API_KEY}
  penn_aspace_api_password:
    external: true
    name: ${FINDING_AID_DISCOVERY_PENN_ASPACE_API_PASSWORD}
  penn_aspace_api_username:
    external: true
    name: ${FINDING_AID_DISCOVERY_PENN_ASPACE_API_USERNAME}
  rails_master_key:
    external: true
    name: ${FINDING_AID_DISCOVERY_RAILS_MASTER_KEY}
  slack_notification_email_address:
    external: true
    name: ${FINDING_AID_DISCOVERY_SLACK_NOTIFICATION_EMAIL_ADDRESS}
