version: "3.8"

services:
  finding_aid_discovery:
    image: ${FINDING_AID_DISCOVERY_IMAGE_NAME}:${FINDING_AID_DISCOVERY_IMAGE_TAG}
    command: ["bin/rails", "server", "-b", "0.0.0.0", "-p", "${FINDING_AID_DISCOVERY_PORT}"]
    deploy:
      placement:
        constraints:
          - "node.labels.finding_aid_discovery == true"
      replicas: ${REPLICAS}
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: /run/secrets/database_password
      DATABASE_USER: ${DATABASE_USER}
      FINDING_AID_DISCOVERY_URL: ${FINDING_AID_DISCOVERY_URL}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsSL localhost:${FINDING_AID_DISCOVERY_PORT} || exit 1",
        ]
      interval: 30s
      retries: 6
      start_period: 30s
      timeout: 30s
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: "10m"
    networks:
      - finding_aid_discovery
      - database
    secrets:
      - database_password

networks:
  finding_aid_discovery:
    driver: overlay
    name: finding_aid_discovery
    attachable: true
  database:
    external: true

secrets:
  database_password:
    external: true
    name: ${DATABASE_PASSWORD}
