version: "3.8"

services:
  finding_aid_discovery:
    image: ${FINDING_AID_DISCOVERY_IMAGE_NAME}:${FINDING_AID_DISCOVERY_IMAGE_TAG}
    command: ["bundle", "exec", "puma", "-b", "tcp://0.0.0.0:${FINDING_AID_DISCOVERY_PORT}"]
    deploy:
      placement:
        constraints:
          - "node.labels.finding_aid_discovery == true"
      replicas: ${REPLICAS}
      update_config:
        order: "start-first"
        parallelism: 1
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: /run/secrets/database_password
      DATABASE_USER: ${DATABASE_USER}
      FINDING_AID_DISCOVERY_URL: ${FINDING_AID_DISCOVERY_URL}
      RAILS_ENV: ${FINDING_AID_DISCOVERY_RAILS_ENV}
      SOLR_URL: "http://solr:8983/solr/${SOLR_CORE_NAME}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsSL localhost:${FINDING_AID_DISCOVERY_PORT} || exit 1",
        ]
      interval: 30s
      retries: 6
      start_period: 30s
      timeout: 30s
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: "10m"
    networks:
      - database
      - finding_aid_discovery
      - solr
    volumes:
      - sitemap:/home/app/public/sitemap
    secrets:
      - database_password
      - slack_notification_email_address
      - honeybadger_api_key
      - penn_aspace_api_password
      - penn_aspace_api_username
      - rails_master_key
networks:
  database:
    external: true
  finding_aid_discovery:
    driver: overlay
    name: finding_aid_discovery
    attachable: true
  solr:
    external: true

secrets:
  database_password:
    external: true
    name: ${DATABASE_PASSWORD}
  honeybadger_api_key:
    external: true
    name: ${FINDING_AID_DISCOVERY_HONEYBADGER_API_KEY}
  penn_aspace_api_password:
    external: true
    name: ${FINDING_AID_DISCOVERY_PENN_ASPACE_API_PASSWORD}
  penn_aspace_api_username:
    external: true
    name: ${FINDING_AID_DISCOVERY_PENN_ASPACE_API_USERNAME}
  rails_master_key:
    external: true
    name: ${FINDING_AID_DISCOVERY_RAILS_MASTER_KEY}
  slack_notification_email_address:
    external: true
    name: ${FINDING_AID_DISCOVERY_SLACK_NOTIFICATION_EMAIL_ADDRESS}

volumes:
  sitemap:
