---
- name: Create custom docker image
  community.docker.docker_image:
    build:
      path: "/finding_aid_discovery/ansible/roles/finding_aid_discovery/files/src/"
      target: development
    force_tag: true
    force_source: true
    name: "{{ finding_aid_discovery_docker_image_name ~ ':' ~ finding_aid_discovery_docker_image_tag }}"
    source: build
    state: present
