---
- name: Create custom docker image
  community.docker.docker_image_build:
    name: "{{ finding_aid_discovery_docker_image_name ~ ':' ~ finding_aid_discovery_docker_image_tag }}"
    path: "/finding_aid_discovery/ansible/roles/finding_aid_discovery/files/src/"
    dockerfile: "Dockerfile"
    target: "development"
    secrets:
      - id: sidekiq_pro_credentials
        type: value
        value: "{{ dld_sidekiq_pro_vault_values.secret.credentials }}"
    args:
      RAILS_ENV: "{{ finding_aid_discovery_rails_env }}"
