---
# If is_development = true and finding_aid_discovery_build_docker_image = false
# Pull existing docker image from the registry to reduce build time
- name: Pull and use docker image from registry
  block:
    # Pull registry image
    - name: Pull the image from the registry
      community.docker.docker_image:
        force_source: true
        force_tag: true
        name: "{{ finding_aid_discovery_docker_image_registry }}:{{ finding_aid_discovery_docker_image_tag }}"
        repository: "{{ finding_aid_discovery_docker_image_name }}:{{ finding_aid_discovery_docker_image_tag }}"
        source: pull
      when: is_development and not finding_aid_discovery_build_docker_image | default(false, true)
      tags: dev_environment
  rescue:
    # An error occurred in the process of pulling the registry so build the image instead
    - name: Failed to find registry image - building image instead
      ansible.builtin.import_tasks: "build_docker_image.yml"
      when: is_development and not finding_aid_discovery_build_docker_image | default(false, true)
      tags: dev_environment

# Build the docker image
- name: "Build docker image"
  ansible.builtin.import_tasks: "build_docker_image.yml"
  when: is_development and finding_aid_discovery_build_docker_image | default(false, true)
  tags: dev_environment

# @tag docker_secrets:description: Create versioned docker secrets
- name: Create versioned docker secrets
  community.docker.docker_secret:
    name: "{{ 'finding_aid_discovery_' ~ item.key ~ '_v' ~ item.value.version }}"
    data: "{{ item.value.value }}"
    state: present
  loop: "{{ finding_aid_discovery_versioned_secrets | dict2items }}"
  tags: versioned_secrets
  no_log: true

- name: Deploy Finding Aids
  community.docker.docker_stack:
    name: "fad"
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"
    state: present
  changed_when: false
