---
postgres:
  database: "finding_aid_discovery"
  image:
    name: "postgres"
    tag: "14"
  replicas: 1
  secrets:
    password:
      value: "{{ finaids_vault_values.secret.database_password }}"
      version: "{{ finaids_vault_values.metadata.version }}"
  user: "finding_aid_discovery"
