---
solr:
  build_docker_image: false
  config_location: "/finding_aid_discovery_configs"
  core_name: "finding-aid-discovery-core"
  image:
    name: "solr"
    registry: "gitlab.library.upenn.edu/dld/finding-aids/solr"
    tag: "{{ image_tag }}"
  java:
    memory:
      min: "2g"
      max: "2g"
  replicas: 1
