---
- name: Create template configs
  docker_config:
    name: "{{ 'nginx_' ~ item.key ~ '_v' ~ item.value.version }}"
    data: "{{ lookup('template', item.value.filename) }}"
    state: present
  with_dict:
    - "{{ nginx.versioned_configs }}"
  changed_when: false
  no_log: true

- name: Set application urls for Traefik
  set_fact:
    application_urls: "{{ nginx.urls | map('regex_replace', '^(.*)$', 'Host(`\\1`)') | join(' || ') }}"

# Deploy nginx
- name: Deploy nginx
  community.docker.docker_stack:
    name: "fad"
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2' ) | from_yaml }}"
    state: present
  changed_when: false
  no_log: false
