---
postgres:
  database: "finding_aid_discovery"
  image:
    name: "postgres"
    tag: "14"
  replicas: 1
  secrets:
    password:
      value: "password"
      version: 1
  user: "finding_aid_discovery"
