---
- name: Create custom docker image
  docker_image:
    build:
      args:
        CONFIG_LOCATION: "{{ solr.config_location }}"
        CORE_NAME: "{{ solr.core_name }}"
      path: "/finding_aid_discovery/ansible/roles/solr/files/src"
      pull: yes
    force_tag: yes
    force_source: yes
    name: "{{ solr.image.name ~ ':' ~ solr.image.tag }}"
    source: build
    state: present
