---
- name: "Install python3-pip and deps with python2"
  block:
    - name: "Install python3-pip"
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: "Install deps with python2"
      ansible.builtin.pip:
        name:
          - jmespath
  vars:
    ansible_python_interpreter: "/usr/bin/python2"

- name: "Install deps"
  ansible.builtin.pip:
    name:
      - jsondiff
      - passlib
      - pyyaml
