---
- name: "Install system-level build dependencies"
  ansible.builtin.package:
    name:
      - python3
      - py3-pip
      - py3-jmespath
      - py3-jsondiff
      - py3-passlib
      - py3-yaml
    state: present

#- name: "Install pip deps"
#  ansible.builtin.package:
#    name:
#      - py3-jsondiff
#      - py3-passlib
#      - py3-yaml
#      - py3-hvac
