---
- name: "Provision Docker Swarm Cluster"
  become: yes
  hosts: all
  pre_tasks:
    - name: Install python3-pip
      package:
        name: python3-pip
        state: present
    - name: Install deps
      pip:
        name:
          - jmespath
  roles:
    - { role: atosatto.docker-swarm }

- hosts: docker_swarm_manager
  become: yes
  gather_facts: true
  tasks:
    - name: Install deps
      pip:
        name:
          - jsondiff
          - passlib
          - pyyaml
      tags: deps
    - import_role:
        name: traefik
      tags: traefik
    - import_role:
        name: postgres
      tags: postgres
    - name: Create solr network
      include_tasks: "roles/solr/tasks/create_solr_network.yml"
      tags: solr
    - import_role:
        name: solr
      tags: solr
    - import_role:
        name: finding_aid_discovery
      tags: finding_aid_discovery
    - import_role:
        name: nginx
      tags: nginx
    - name: Recursively remove project directory
      file:
        path: "{{ project_root }}"
        state: absent
