---
- name: "Provision Docker Swarm Cluster"
  hosts: all
  become: true
  tasks:
    - ansible.builtin.import_tasks: "provision_docker.yml"

- name: "Deploy application"
  hosts: docker_swarm_manager
  become: true
  gather_facts: true
  tasks:
    - import_role:
        name: traefik
      tags: traefik
    - import_role:
        name: postgres
      tags: postgres
    - name: Create solr network
      include_tasks: "roles/solr/tasks/create_solr_network.yml"
      tags: solr
    - import_role:
        name: solr
      tags: solr
    - import_role:
        name: finding_aid_discovery
      tags: finding_aid_discovery
    - import_role:
        name: redis
      tags: redis
    - import_role:
        name: sidekiq
      tags: sidekiq
    - import_role:
        name: nginx
      tags: nginx
    - import_role:
        name: chrome
      tags: chrome
      when: is_development | default (false) == true
  post_tasks:
    - name: Recursively remove project directory
      file:
        path: "{{ project_root }}"
        state: absent
    - name: Prune images that are older than 2+ hours
      docker_prune:
        images: yes
        images_filters:
          dangling: false
          until: 2h
      when: not is_development | default (false) == true
