---
- name: "Provision Docker Swarm Cluster"
  hosts: docker_swarm_manager
  become: true
  tasks:
    - name: "Import docker provisioning tasks"
      ansible.builtin.import_tasks: "provision_docker.yml"

- name: "Deploy application"
  hosts: docker_swarm_manager
  become: true
  gather_facts: true
  tasks:
    - name: "Import app symlink"
      ansible.builtin.import_role:
        name: finding_aid_discovery
        tasks_from: symlink_project
      tags: finding_aid_discovery
    - name: "Import traefik"
      ansible.builtin.import_role:
        name: traefik
      tags: traefik
    - name: "Import postgres"
      ansible.builtin.import_role:
        name: postgres
      tags: postgres
    - name: "Import zookeeper"
      ansible.builtin.import_role:
        name: zookeeper
      tags: zookeeper
    - name: "Import zoonavigator"
      ansible.builtin.import_role:
        name: zoonavigator
      tags: zoonavigator
      when: not is_development | default(false, true)
    - name: "Import solr"
      ansible.builtin.import_role:
        name: solr
      tags: solr
    - name: "Import redis"
      ansible.builtin.import_role:
        name: redis
      tags: redis
    - name: "Import finding_aid_discovery"
      ansible.builtin.import_role:
        name: finding_aid_discovery
      tags: finding_aid_discovery
    - name: "Import sidekiq"
      ansible.builtin.import_role:
        name: sidekiq
      tags: sidekiq
    - name: "Import chrome"
      ansible.builtin.import_role:
        name: chrome
      tags: chrome
      when: is_development | default(false, true)
  post_tasks:
    - name: Recursively remove project directory
      ansible.builtin.file:
        path: "{{ project_root }}"
        state: absent
    - name: Prune images that are older than 2+ hours
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: false
          until: 2h
      when: not is_development | default(false, true)
