---
- name: "Set up Docker and Docker Swarm"
  hosts: all
  become: true
  gather_facts: true
  roles:
    - docker-swarm
    
- name: "Deploy application"
  hosts: docker_swarm_managers
  become: true
  gather_facts: false
  tasks:
    - name: Force latest version of requests
      ansible.builtin.pip:
        name: jsondiff
        state: present
    - name: Deploy Traefik
      ansible.builtin.import_role:
        name: traefik
      tags:
        - traefik
    - name: Deploy Zookeeper
      ansible.builtin.import_role:
        name: zookeeper
      tags: 
        - zookeeper
    - name: Deploy Solr
      ansible.builtin.import_role:
        name: solr
      tags: 
        - solr
    - name: Deploy Redis
      ansible.builtin.import_role:
        name: redis
      tags: 
        - redis
    - name: Deploy Postgres
      ansible.builtin.import_role:
        name: postgres
      tags: 
        - postgres
    - name: Deploy finding_aid_discovery
      ansible.builtin.import_role:
        name: finding_aid_discovery
      tags: finding_aid_discovery
    - name: Deploy sidekiq
      ansible.builtin.import_role:
        name: sidekiq
      tags: sidekiq
    - name: Deploy chrome
      ansible.builtin.import_role:
        name: chrome
      tags: chrome
      when: is_development | default(false, true)
  post_tasks:
    - name: Recursively remove project directory
      ansible.builtin.file:
        path: "{{ project_root }}"
        state: absent
    - name: Prune images that are older than 2+ hours
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: false
          until: 2h
      when: not is_development | default(false, true)
