---
- name: "Set up for vault file interaction"
  hosts: docker_swarm_manager
  become: true
  pre_tasks:
    - name: Install python3-pip
      package:
        name: python3-pip
        state: present
    - name: Install deps
      pip:
        name:
          - hvac
  tasks:
    - name: Make the Ansible client script executable
      file:
        dest: /finding_aid_discovery/ansible/vault_passwd-client.py
        mode: a+x

- import_playbook: site.yml
