- name: "Set up nginx reverse proxy with ssl termination to mimic a reverse-proxy/loadbalancer"
  hosts: docker_swarm_manager
  become: true
  collections:
    - nginxinc.nginx_core
  pre_tasks:
    - name: Create a self-signed cert for nginx
      command: >
        openssl req -x509 -nodes -subj "/CN={{ url }}" -days 365  -addext "subjectAltName = DNS:{{ url }}"
        -newkey rsa:4096 -sha256 -keyout {{ proxy.ssl.key.location }} -out {{ proxy.ssl.crt.location }}
        creates={{ proxy.ssl.crt.location }}
  roles:
    - role: nginx
    - role: nginx_config
      vars:
        nginx_config_http_template_enable: true
        nginx_config_http_template:
          app:
            template_file: http/default.conf.j2
            conf_file_name: default.conf
            conf_file_location: /etc/nginx/conf.d/
            servers:
              main:
                listen:
                  listen_main:
                    ip: 0.0.0.0
                    port: 443
                    ssl: true
                server_name: "{{ url }}"
                ssl:
                  cert: "{{ proxy.ssl.crt.location }}"
                  key: "{{ proxy.ssl.key.location }}"
                access_log:
                  - name: main
                    location: /var/log/nginx/access.log
                error_log:
                  location: /var/log/nginx/error.log
                  level: warn
                reverse_proxy:
                  locations:
                    main:
                      location: /
                      proxy_pass: "http://127.0.0.1:80"
                      proxy_set_header:
                        header_host:
                          name: Host
                          value: $host
                        header_x_real_ip:
                          name: X-Real-IP
                          value: $remote_addr
                        header_x_forwarded_for:
                          name: X-Forwarded-For
                          value: $proxy_add_x_forwarded_for
                        header_x_forwarded_proto:
                          name: X-Forwarded-Proto
                          value: $scheme

- import_playbook: site.yml
