version: "3.8"

services:
  traefik:
    image: ${TRAEFIK_IMAGE_NAME}:${TRAEFIK_IMAGE_TAG}
    command:
      - "--accesslog=true"
      - "--api.dashboard=${TRAEFIK_DASHBOARD_ENABLE}"
      - "--entrypoints.metrics.address=:8082"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"
      - "--entrypoints.traefik.address=:${TRAEFIK_DASHBOARD_PORT}"
      - "--log.level=${TRAEFIK_LOG_LEVEL}"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entrypoint=metrics"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.swarmModeRefreshSeconds=15"
      - "--providers.docker.watch=true"
    deploy:
      labels:
        - "traefik.enable=true"

        # dashboard rules
        - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_URL}`)"
        - "traefik.http.routers.dashboard.entrypoints=traefik"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/users"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.services.dashboard.loadbalancer.server.port=${TRAEFIK_DASHBOARD_PORT}"
      placement:
        constraints:
          - "node.labels.traefik==true"
      replicas: 1
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: "10m"
    ports:
      - "80:80"
      - "8082:8082"
      - "${TRAEFIK_DASHBOARD_PORT}:${TRAEFIK_DASHBOARD_PORT}"
    secrets:
      - source: middlewares_users
        target: /etc/traefik/users
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

networks:
  traefik:
    driver: overlay
    name: traefik
    attachable: true

secrets:
  middlewares_users:
    external: true
    name: ${TRAEFIK_MIDDLEWARES_USERS_NAME}
