default: &default
  adapter: postgresql
  database: <%= ENV.fetch('DATABASE_NAME', 'finding_aid_discovery_development') %>
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST', 'postgres') %>
  password: <%= File.exist?('/run/secrets/database_password') ? File.read('/run/secrets/database_password').strip : ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>
development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
