default: &default
  adapter: postgresql
  database: <%= ENV['DATABASE_NAME'] %>
  encoding: unicode
  host: postgres
  password: <%= File.exist?('/run/secrets/database_password') ? File.read('/run/secrets/database_password').strip : ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
