# Jobs scheduled via sidekiq-cron

harvest_all:
  cron: "0 5 * * 1,3,5" # 5AM MWF
  class: "PartnerHarvestEnqueueJob"
  description: "Enqueues PartnerHarvestJobs for all Endpoints sorted by oldest updated_at value"
  active_job: true
delete_searches:
  cron: "0 1 * * *" # Daily
  class: "DeleteSearchesJob"
  description: "Remove searches that are older than 7 days"
  active_job: true