// Auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller.
import { application } from "controllers/application"

import MapController from "controllers/map_controller"
application.register("map", MapController)
