---
- name: Create custom docker image
  docker_image:
    build:
      path: "{{ finding_aid_discovery.dev.build_path }}"
      pull: yes
      target: development
    force_tag: yes
    force_source: yes
    name: "{{ finding_aid_discovery.image.name ~ ':' ~ finding_aid_discovery.image.tag }}"
    source: build
    state: present
